"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import MeetingCard from "@/components/MeetingCard";
import { Card, CardContent } from "@/components/ui/card";
import { AudioLines, ArrowLeft, Sparkles } from "lucide-react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { getMeetingsApiUrl } from "@/lib/meetings-api";

interface Topic {
  topic: string;
  relevance_score: number;
}

interface Meeting {
  id: number;
  meeting_title: string;
  participant_count: number;
  transcript_length: number;
  summary: string;
  topics: Topic[];
}

export default function MeetingsPage() {
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    fetch(`${getMeetingsApiUrl()}/meetings`)
      .then((res) => {
        if (!res.ok) throw new Error("Failed to fetch meetings");
        return res.json();
      })
      .then((data) => {
        setMeetings(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setError("Failed to load meetings");
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <>
        <Navbar />
        <div className="min-h-screen bg-background flex items-center justify-center">
          <div className="text-center">
            <div className="size-12 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-muted-foreground">Loading meetings...</p>
          </div>
        </div>
        <Footer />
      </>
    );
  }

  if (error) {
    return (
      <>
        <Navbar />
        <div className="min-h-screen bg-background flex items-center justify-center px-4">
          <Card className="w-full max-w-md border-border/70 shadow-lg">
            <CardContent className="p-8 text-center">
              <div className="size-16 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-4">
                <svg
                  className="size-8 text-destructive"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </div>
              <h2 className="text-xl font-bold font-heading mb-2">Error</h2>
              <p className="text-muted-foreground">{error}</p>
            </CardContent>
          </Card>
        </div>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-background">
        {/* Hero Section */}
        <section className="border-b border-border/70 bg-muted/20">
          <div className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-6"
            >
              <ArrowLeft className="size-4" />
              Back to Home
            </Link>
            
            <div className="flex items-center gap-3 mb-4">
              <div className="flex size-12 items-center justify-center rounded-lg bg-primary/10 border border-primary/20">
                <Sparkles className="size-6 text-primary" aria-hidden="true" />
              </div>
              <div className="inline-flex items-center gap-2 rounded-full border border-border/70 bg-background px-3 py-1 text-xs font-medium text-muted-foreground shadow-sm">
                <AudioLines className="size-3.5 text-primary" aria-hidden="true" />
                AI-Powered Meeting Intelligence
              </div>
            </div>

            <h1 className="text-balance font-heading text-4xl font-semibold tracking-tight text-foreground sm:text-5xl mb-4">
              AI Meeting Summaries
            </h1>
            <p className="max-w-2xl text-pretty text-base leading-7 text-muted-foreground sm:text-lg">
              Access all your analyzed meetings with structured summaries, action items, and speaker insights generated by AI.
            </p>

            {/* Stats */}
            {meetings.length > 0 && (
              <dl className="mt-8 grid max-w-2xl grid-cols-1 gap-3 sm:grid-cols-3">
                <div className="rounded-lg border border-border/70 bg-background/90 p-4 shadow-sm">
                  <dt className="text-xs font-medium text-muted-foreground">
                    Total Meetings
                  </dt>
                  <dd className="mt-2 font-heading text-2xl font-semibold text-foreground">
                    {meetings.length}
                  </dd>
                </div>
                <div className="rounded-lg border border-border/70 bg-background/90 p-4 shadow-sm">
                  <dt className="text-xs font-medium text-muted-foreground">
                    Total Participants
                  </dt>
                  <dd className="mt-2 font-heading text-2xl font-semibold text-foreground">
                    {meetings.reduce((sum, m) => sum + m.participant_count, 0)}
                  </dd>
                </div>
                <div className="rounded-lg border border-border/70 bg-background/90 p-4 shadow-sm">
                  <dt className="text-xs font-medium text-muted-foreground">
                    Avg. Transcript Length
                  </dt>
                  <dd className="mt-2 font-heading text-2xl font-semibold text-foreground">
                    {Math.round(meetings.reduce((sum, m) => sum + m.transcript_length, 0) / meetings.length)}
                  </dd>
                </div>
              </dl>
            )}
          </div>
        </section>

        {/* Meetings Grid Section */}
        <section className="px-6 py-16 lg:px-8">
          <div className="mx-auto max-w-7xl">
            {meetings.length === 0 ? (
              <Card className="border-border/70 shadow-sm">
                <CardContent className="p-16 text-center">
                  <div className="size-20 rounded-full bg-muted/50 flex items-center justify-center mx-auto mb-6">
                    <AudioLines className="size-10 text-muted-foreground" />
                  </div>
                  <h2 className="text-2xl font-bold font-heading mb-3">No Meetings Yet</h2>
                  <p className="text-muted-foreground text-base mb-6 max-w-md mx-auto">
                    Your analyzed meetings will appear here. Start recording from Google Meet to generate AI-powered summaries.
                  </p>
                  <Link
                    href="/"
                    className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
                  >
                    Get Started
                  </Link>
                </CardContent>
              </Card>
            ) : (
              <>
                <div className="mb-6">
                  <h2 className="text-2xl font-semibold font-heading text-foreground">
                    Recent Meetings
                  </h2>
                  <p className="text-sm text-muted-foreground mt-1">
                    Click on any meeting to view detailed analysis
                  </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {meetings.map((meeting) => (
                    <MeetingCard key={meeting.id} meeting={meeting} />
                  ))}
                </div>
              </>
            )}
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
